import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppContainer from '@/app/containers/AppContainer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'nearme',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <AppContainer>
        <body className={inter.className}>
          {children}
          <script
            async
            src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC__GOOGLEMAPS_API_KEY}&loading=async&libraries=places&callback=initMap`}
          ></script>
        </body>
      </AppContainer>
    </html>
  );
}
